name: GitHub Activity Dashboard

on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    dashboard:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Configure Git
              run: |
                  git config user.name "andrast32"
                  git config user.email "52090531+andrast32@users.noreply.github.com"

            - name: Update files
              shell: bash
              run: |
                  LAST_UTC=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
                  NEXT_UTC=$(date -u -d "+1 hour" +"%Y-%m-%d %H:%M:%S UTC")
                  
                  LAST_WIB=$(TZ=Asia/Jakarta date +"%Y-%m-%d %H:%M:%S WIB")
                  NEXT_WIB=$(TZ=Asia/Jakarta date -d "+1 hour" +"%Y-%m-%d %H:%M:%S WIB")

                  printf "GitHub Green Bot\n\nStatus : ONLINE\n\nLast Update\nUTC : %s\nWIB : %s\n\nNext Update\nUTC : %s\nWIB : %s\n" \
                  "$LAST_UTC" "$LAST_WIB" "$NEXT_UTC" "$NEXT_WIB" > keepalive.txt

                  {
                    echo "# GitHub Activity Dashboard"
                    echo ""
                    echo "## Status"
                    echo ""
                    echo "| Item | Value |"
                    echo "|------|-------|"
                    echo "| Status | 🟢 ONLINE |"
                    echo "| Schedule | Every 1 Hour |"
                    echo "| Owner | ${{ github.repository_owner }} |"
                    echo "| Repository | ${{ github.event.repository.name }} |"
                    echo ""
                    echo "## Last Update"
                    echo ""
                    echo "- UTC : $LAST_UTC"
                    echo "- WIB : $LAST_WIB"
                    echo ""
                    echo "## Next Update"
                    echo ""
                    echo "- UTC : $NEXT_UTC"
                    echo "- WIB : $NEXT_WIB"
                  } > README.md

            - name: Commit
              run: |
                  git add .
                  git diff --cached --quiet && exit 0
                  git commit -m "Auto Update"

            - name: Push
              run: git push
