name: Daily Green

on:
  schedule:
    # 00:00 UTC = 07:00 WIB jadi update per 1 jam sekali
     - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  green:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update file
        run: |
          echo "Last update: $(date -u)" > keepalive.txt

      - name: Commit
        run: |
          git add .
          git diff --cached --quiet || git commit -m "🌱 Daily contribution"

      - name: Push
        run: |
          git push